"""add family_id to refresh_tokens for rotation reuse detection

Revision ID: ee4b8917121f
Revises: 14ed50e312b7
Create Date: 2026-05-10 12:22:43.240016+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4b8917121f'
down_revision: Union[str, Sequence[str], None] = '14ed50e312b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 기존 행이 있을 수 있으므로 nullable=True로 추가 → 백필 → NOT NULL.
    op.add_column('refresh_tokens', sa.Column('family_id', sa.String(length=64), nullable=True))
    # 기존 토큰은 자기 자신을 family로 (회전 이력 없음 — 어차피 다음 refresh에서 새 family 부여됨).
    op.execute("UPDATE refresh_tokens SET family_id = jti WHERE family_id IS NULL")
    op.alter_column('refresh_tokens', 'family_id', nullable=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'family_id')
    # ### end Alembic commands ###
