"""add marketing_consents table

Revision ID: bd5762f510e0
Revises: 85d7e1b07a56
Create Date: 2026-05-19 05:27:48.763121+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5762f510e0'
down_revision: Union[str, Sequence[str], None] = '85d7e1b07a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketing_consents',
    sa.Column('consent_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('night_time_opt_in', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.String(length=20), server_default='V1', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consent_id')
    )
    op.create_index(op.f('ix_marketing_consents_recorded_at'), 'marketing_consents', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_marketing_consents_user_id'), 'marketing_consents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketing_consents_user_id'), table_name='marketing_consents')
    op.drop_index(op.f('ix_marketing_consents_recorded_at'), table_name='marketing_consents')
    op.drop_table('marketing_consents')
    # ### end Alembic commands ###
