"""initial

Revision ID: 772ef94b8925
Revises: 
Create Date: 2026-05-07 13:10:01.901966+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '772ef94b8925'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('backtest_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.Column('violation_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('miss_count', sa.Integer(), nullable=True),
    sa.Column('hit_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('avg_violation_depth', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('kupiec_statistic', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('kupiec_p_value', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('run_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('backtest_id')
    )
    op.create_index('idx_backtest_ticker_run', 'backtest_results', ['ticker', 'run_at'], unique=False)
    op.create_table('macro_indicators',
    sa.Column('indicator_code', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.PrimaryKeyConstraint('indicator_code', 'trade_date')
    )
    op.create_table('tickers',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('company_name_kr', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), server_default='USD', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('disclaimer_acks',
    sa.Column('ack_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('disclaimer_code', sa.String(length=50), nullable=False),
    sa.Column('acknowledged_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ack_id')
    )
    op.create_index(op.f('ix_disclaimer_acks_user_id'), 'disclaimer_acks', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('q05_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('q15_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('q50_path', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('worst_case_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('ticker', 'base_date', 'horizon_days', name='uq_predictions_ticker_base_horizon')
    )
    op.create_index(op.f('ix_predictions_ticker'), 'predictions', ['ticker'], unique=False)
    op.create_table('prices',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('dividends', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('stock_splits', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('trade_date', 'ticker')
    )
    op.create_index(op.f('ix_prices_ticker'), 'prices', ['ticker'], unique=False)
    op.create_table('watchlist',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'ticker')
    )
    op.create_table('analysis_history',
    sa.Column('analysis_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('grade', sa.String(length=30), nullable=False),
    sa.Column('worst_case_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('price_at_query', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('queried_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('outcome_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('outcome_evaluated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index('idx_analysis_user_queried', 'analysis_history', ['user_id', 'queried_at'], unique=False)
    op.create_table('prediction_evaluations',
    sa.Column('evaluation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.Column('predicted_q05_min', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('actual_min_return', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('actual_end_return', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('is_violated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evaluation_id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_index(op.f('ix_prediction_evaluations_ticker'), 'prediction_evaluations', ['ticker'], unique=False)
    op.create_table('risk_grades',
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('grade', sa.String(length=30), nullable=False),
    sa.Column('message_code', sa.String(length=50), nullable=False),
    sa.Column('worst_case_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticker'], ['tickers.ticker'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_risk_grades_prediction_id'), 'risk_grades', ['prediction_id'], unique=False)
    op.create_table('xai_explanations',
    sa.Column('xai_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('xai_id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_index(op.f('ix_xai_explanations_ticker'), 'xai_explanations', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xai_explanations_ticker'), table_name='xai_explanations')
    op.drop_table('xai_explanations')
    op.drop_index(op.f('ix_risk_grades_prediction_id'), table_name='risk_grades')
    op.drop_table('risk_grades')
    op.drop_index(op.f('ix_prediction_evaluations_ticker'), table_name='prediction_evaluations')
    op.drop_table('prediction_evaluations')
    op.drop_index('idx_analysis_user_queried', table_name='analysis_history')
    op.drop_table('analysis_history')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_prices_ticker'), table_name='prices')
    op.drop_table('prices')
    op.drop_index(op.f('ix_predictions_ticker'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_disclaimer_acks_user_id'), table_name='disclaimer_acks')
    op.drop_table('disclaimer_acks')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tickers')
    op.drop_table('macro_indicators')
    op.drop_index('idx_backtest_ticker_run', table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
